services:
  - type: web
    name: fifo-inventory-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FIREBASE_CREDENTIALS
        sync: false
